"""New Migration

Revision ID: 1149b2596ca0
Revises: 3e82be47f3ce
Create Date: 2023-01-10 13:26:57.109628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1149b2596ca0'
down_revision = '3e82be47f3ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
