"""New Migration

Revision ID: 3e82be47f3ce
Revises: 31c0367d86ec
Create Date: 2023-01-10 13:16:46.402435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e82be47f3ce'
down_revision = '31c0367d86ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
