"""New Migration

Revision ID: 8c344a134709
Revises: d05e0fd0afb5
Create Date: 2023-02-05 17:01:15.336150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c344a134709'
down_revision = 'd05e0fd0afb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
