"""New Migration

Revision ID: b00b2a37ab79
Revises: 1149b2596ca0
Create Date: 2023-01-10 13:44:03.702143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00b2a37ab79'
down_revision = '1149b2596ca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
