"""New Migration

Revision ID: e7550477c1ca
Revises: 54e6f3bdf565
Create Date: 2023-01-10 13:08:31.675377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7550477c1ca'
down_revision = '54e6f3bdf565'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('comment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=False)
    op.create_table('loyalty_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_limit', sa.Integer(), nullable=True),
    sa.Column('if_premium', sa.Boolean(), nullable=True),
    sa.Column('subscription_plan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_plan_id'), 'loyalty_plan', ['id'], unique=False)
    op.add_column('offer', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offer', 'comment', ['comment_id'], ['id'])
    op.add_column('user', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'comment_id')
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_column('offer', 'comment_id')
    op.drop_index(op.f('ix_loyalty_plan_id'), table_name='loyalty_plan')
    op.drop_table('loyalty_plan')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
